import enum

class ActionType(enum.Enum):
    PARKINGLIST = 1
    REPORTEDINCIDENTSlIST = 2
    WEATHERINFO = 3
    AIRQUALITYINFO = 4
    CONNECTAGENT = 5
    BUSSTOPSLIST = 6
    BUSDEPOTLIST = 7
    BUSTRIPPLANNERINFO = 8
    BUSTRIPDETAILS = 9
    HELPOPTIONS = 10
    GARBAGE_SUB_SERVICES = 11 
    WATER_SUB_SERVICES = 12
    ELECTRICITY_SUB_SERVICES = 13
    NEARBY_BIN_LOC = 14
    CONTACT_INFO = 15
    BUS_ROUTE_NAME_INFO = 16
    BUS_ROUTE_DETAILS_INFO = 17
    POLICE_CONTACT_INFO = 18
    FIRE_CONTACT_INFO = 19
    AMBULANCE_CONTACT_INFO = 20
    GREET_SUGGESTION = 21
    TRANSPORT_SUB_SERVICES = 22
    BUS_CONTACT_INFO = 23
    NEAREST_HOSPITALS = 24
    POLICE_STATION_INFO=25
    FIRE_STATION_INFO=26
    GARBAGE_CONTACT_INFO=27
    AUDIO_ATTACHMENT = 28
    DOC_ATTACHMENT = 29
    VIDEO_ATTACHMENT = 30
    CHAT_BOT_ICON = 31
    NEAREST_TOURIST_PLACE = 32
    TWO_WHEELER_PARKINGLIST = 33
    POLICE_VEHICLE_LOCATION = 35