'''
all actions must be imported here
is available from rasa endpoint
'''

from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
from __future__ import unicode_literals

import logging

from chatbot_actions.actions import *
from chatbot_actions.civicComplaint import *
from chatbot_actions.civicIssue_street import *
from chatbot_actions.civicIssue_swm import *
from chatbot_actions.service_types.ServiceIssueType import *
from chatbot_actions.itms.transportServicesActions import ITMS_BestRoute, ITMSNearestBustop, ITMSBusDepot, BusRouteNameInfo, BusRouteDetailsInfo, TransportServices
from chatbot_actions.civicServices import ActionUpdateUserIncidentRemarks
from chatbot_actions.swm.swmServiceActions import ReportToSWMAsGarbageBinFull, GarbagePickupService, GarbageBinLocation, GarbageServices
from chatbot_actions.bot_services.bot_service import BotActionService, BotService
from chatbot_actions.parking.parking import ParkingService
from chatbot_actions.weather.weatherapi import CityCurrentWheatherInfo, getHourlyForcastInfo, getlocationKey
from chatbot_actions.air_quality.airqualityservice import CityAirQualityInfo
from chatbot_actions.connectAgent.connectagentservice import ConnectAgentService
from chatbot_actions.electricity.electricity_services import ElectricityServices, ElectricityAccBalanceInfo
from chatbot_actions.water.water_services import WaterServices, NewWaterConnection, WaterScheduleService
from chatbot_actions.contact_service.contactService import ContactService
from chatbot_actions.contact_service.contactService import PoliceStationContactService
from chatbot_actions.contact_service.contactService import FireContactService
from chatbot_actions.contact_service.contactService import AmbulanceContactService
from chatbot_actions.launch_service.greeting_message import HelpSuggestion
from chatbot_actions.emergency_service.emergencyServiceAction import NearestPoliceStation
from chatbot_actions.emergency_service.emergencyServiceAction import NearestFireStation
from chatbot_actions.emergency_service.emergencyServiceAction import HospitalInfo
from chatbot_actions.emergency_service.emergencyServiceAction import PoliceVehicleLocation
from chatbot_actions.emergencyComplaint import *