policies:
  - name: KerasPolicy
    epochs: 20
    max_history: 5
  - name: FallbackPolicy
    fallback_action_name: 'action_fallback'
  - name: MemoizationPolicy
    max_history: 1
  - name: FormPolicy
    