language: "en"

pipeline:
- name: "tokenizer_whitespace"
- name: "ner_crf"
- name: "ner_synonyms"
- name: "intent_featurizer_count_vectors"
- name: "intent_classifier_tensorflow_embedding"
# - name: "ner_duckling"
#   # dimensions to extract
#   dimensions: ["time", "number", "amount-of-money", "distance"]
#   # allows you to configure the locale, by default the language is
#   # used
#   locale: "en"
#   # if not set the default timezone of Duckling is going to be used
#   # needed to calculate dates from relative expressions like "tomorrow"
#   timezone: "Asia/Kolkata"
path: ./models/nlu
data: ./data/training_nlu.json
